# Generated by Django 5.0.6 on 2024-06-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autentificar', '0002_remove_alumno_carrera_remove_docente_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(default='example', max_length=100),
            preserve_default=False,
        ),
    ]
