# Generated by Django 5.0.6 on 2024-06-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_inscripcion_evaluacion_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='evaluacion_docente',
        ),
    ]
